Fixing command sizing and changing the test to issue the maximum number of packets the queue supports.
nod-ai/ROCR-Runtime pull request #23
Opened 2024-09-11 19:34 UTC by eddierichter-amd

Made the following changes:
- Fixed workarounds in the AIE soft queue regarding the size of the command chain and the individual commands. 
- Added the functionality to `aie_hsa_dispatch_test.cc` to query the size of the AIE queue and issue the maximum number of packets it supports. 
- Some additional small fixes on `aie_hsa_dispatch_test.cc` test.

2024-09-11 19:41 UTC, ypapadop-amd requested changes

2024-09-11 19:41 UTC, ypapadop-amd commented on rocrtst/suites/aie/aie_hsa_dispatch_test.cc
> +  hsa_agent_get_info(aie_agent, HSA_AGENT_INFO_QUEUE_MAX_SIZE, &aie_max_queue_size);
Needs assert for the returned status.

2024-09-11 19:41 UTC, ypapadop-amd commented on rocrtst/suites/aie/aie_hsa_dispatch_test.cc
> +    hsa_amd_aie_ert_packet_t *cmd_pkt = reinterpret_cast<hsa_amd_aie_ert_packet_t *>(
Since `base_address` is a void*, static_cast would be more appropriate here.

2024-09-11 19:41 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +constexpr int CMD_COUNT_SIZE_INCREASE = 3;
Can we get this size from the driver?

2024-09-11 19:41 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +        cmd_chain->count = sizeof(amdxdna_cmd_chain) + cmd_handles.size() * sizeof(uint64_t);
Why are these handles uint64_t?

2024-09-11 19:45 UTC, eddierichter-amd commented on rocrtst/suites/aie/aie_hsa_dispatch_test.cc
> +  hsa_agent_get_info(aie_agent, HSA_AGENT_INFO_QUEUE_MAX_SIZE, &aie_max_queue_size);
Good catch. Thanks!

2024-09-11 19:45 UTC, eddierichter-amd commented on rocrtst/suites/aie/aie_hsa_dispatch_test.cc
> +    hsa_amd_aie_ert_packet_t *cmd_pkt = reinterpret_cast<hsa_amd_aie_ert_packet_t *>(
Good catch. Thanks!

2024-09-11 19:51 UTC, eddierichter-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +        cmd_chain->count = sizeof(amdxdna_cmd_chain) + cmd_handles.size() * sizeof(uint64_t);
Not sure but this is what the xdna driver is using https://github.com/amd/xdna-driver/blob/main/src/driver/amdxdna/amdxdna_ctx.h#L64

2024-09-11 20:28 UTC, eddierichter-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +constexpr int CMD_COUNT_SIZE_INCREASE = 3;
That would be really nice but not sure the best way to do that. The reason it is `3` is because the driver sets the size of the command in the chain here https://github.com/amd/xdna-driver/blob/main/src/driver/amdxdna/aie2_message.c#L632 which uses the size of this struct https://github.com/amd/xdna-driver/blob/main/src/driver/amdxdna/aie2_msg_priv.h#L388-L392. We don't have a need to have this `cmd_chain_slot_execbuf_cf ` struct in the runtime but can copy it over if we want to get the size. We could be more programmatic with an ioctl but that might be overkill. Thoughts?

2024-09-11 20:50 UTC, makslevental commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +constexpr int CMD_COUNT_SIZE_INCREASE = 3;
I love the comment there:

```
/* Accurate buf size to hint firmware to do necessary copy */
```

What happens in the FW doesn't take the hint I wonder :thinking: 

Anyway my thought is it's just a matter of API - xdna should have a more visible API but it doesn't so the only thing we can do is document and leave breadcrumbs. So can you please leave these exact lines in the comment (with the hash, i.e. go to the link and hit `y` on your keyboard).

2024-09-11 22:54 UTC, eddierichter-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp
> +constexpr int CMD_COUNT_SIZE_INCREASE = 3;
Works with me!

2024-09-12 00:54 UTC, ypapadop-amd approved these changes
LGTM

2024-09-12 06:58 UTC, makslevental approved these changes
LGTM

2024-09-12 15:42 UTC, merged