Import/export for AIEs via vmem API
nod-ai/ROCR-Runtime pull request #25
Opened 2024-09-16 20:24 UTC by ypapadop-amd

This PR allows sharing GPU memory with AIE agents via the vmem API. Sharing via other alternatives (hsa_amd_memory_lock, hsa_amd_interop_map_buffer, hsa_amd_agents_allow_access) is not allowed and will throw an error.

2024-09-16 20:25 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +  if (munmap(va, size) != 0)
I'm not entirely sure if this is the correct way for XDNA to remove access.

2024-09-16 20:28 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/inc/runtime.h
> -    uint64_t mmap_offset;
This was not used anywhere and I accidentally typed it in. Removing it so people don't do the same mistake.

2024-09-16 20:28 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_agent.cpp
> +  auto &driver = static_cast<XdnaDriver &>(
We do constant lookups for the driver. I think that caching a pointer to the driver would be the best solution.

2024-09-16 20:29 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_gpu_agent.cpp
> +const uint32_t GpuAgent::minAqlSize_;
If you compile with debug, the inline declared statics, even though const, don't have an associated definition. This leads to linked errors.

2024-09-16 20:30 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<GpuAgentInt*> whitelist_gpus;
Never used.

2024-09-16 20:30 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<core::Agent*> whitelist_gpus;
Never used.

2024-09-16 20:31 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/runtime.cpp
> +    return status;
I think that this is a create shareable handle process.

2024-09-16 20:31 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/runtime.cpp
> +        size);
Checking if this is indeed RemoveAccess (it seems so).

2024-09-16 20:36 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/runtime.cpp
> +    offset = reinterpret_cast<uint64_t>(mappedHandle->drm_cpu_addr);
I'm not entirely sure about why this is different.

2024-09-16 22:29 UTC, makslevental commented on runtime/hsa-runtime/core/runtime/amd_gpu_agent.cpp
> +const uint32_t GpuAgent::minAqlSize_;
cool - i was just `sed`ing out the `static` because I wasn't sure if this was intentional (in the standard link path I see `--whole-archive`...).

2024-09-16 22:35 UTC, atgutier requested changes
Need to do a deeper review of the core changes, but wanted to request some changes, particular regarding the agent API first.

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +hsa_status_t XdnaDriver::ImportDMABuf(int dmabuf_fd, uint32_t *handle) {
Can handle be made a reference?

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +  if (munmap(va, size) != 0)
If a VA range was allocated using mmap(), even if on a driver FD, this should be the correct way to remove the VA range.

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/inc/agent.h
>  // Copyright (c) 2014-2020, Advanced Micro Devices, Inc. All rights reserved.
I suppose this should be updated to include 2024?

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +__forceinline int mmap_perm(hsa_access_permission_t perms) {
I wonder if this is general enough to be a static method in the base driver? Or a function defined in a global driver-related header?

If we leave it here in this cpp file, should we put it in an anonymous namespace?

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +hsa_status_t XdnaDriver::ImportDMABuf(int dmabuf_fd, uint32_t *handle) {
I'm thinking we may want to change our driver interface wherever a handle is passed to use:

hsa_amd_vmem_alloc_handle_t

It is defined in hsa_ext_amd.h for referring to memory allocation handles. In any case, I think we'd at least need to use uint64_t for handles since this is what the KFD uses.

There may be some uint32_t handles from my prior changes that we'd need to update.

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/inc/agent.h
> +  virtual hsa_status_t Map(void *handle, void *va, size_t offset, size_t size,
These should be members of the Driver as the other OS driver functions are, not the agent. It'd warrant much broader/deeper discussion if we want to expose these in the Agent API.

2024-09-16 22:35 UTC, atgutier commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<core::Agent*> whitelist_gpus;
I think you may want to make a separate change for this and get David's feedback. He's mentioned this code to me in the past, although I have to admit I never bothered to understand how it works. Weird that it'd be unused though.

2024-09-17 00:13 UTC, makslevental commented on runtime/hsa-runtime/core/inc/agent.h
>  // Copyright (c) 2014-2020, Advanced Micro Devices, Inc. All rights reserved.
copyright's aren't supposed to be updated - doing so in effect waives your rights for the years you "bumped" past.

2024-09-17 00:38 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/inc/agent.h
> +  virtual hsa_status_t Map(void *handle, void *va, size_t offset, size_t size,
There's a tricky part. GpuAgent::ImportDMABuf uses GpuAgent::libDrmDev() which is set by hsaKmtGetAMDGPUDeviceHandle(node_id(), &device_handle);

If we were to move it into the driver, for every import we would be adding a lookup for the driver type (we should probably cache that one) and an ioctl. 

The rest of the functions can be moved to the driver, but then we'll have one function in the agent and the rest in the driver. Maybe have the import / export in the agent and the rest in the driver?

2024-09-17 00:40 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +hsa_status_t XdnaDriver::ImportDMABuf(int dmabuf_fd, uint32_t *handle) {
Yes.

2024-09-17 00:44 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +hsa_status_t XdnaDriver::ImportDMABuf(int dmabuf_fd, uint32_t *handle) {
That's the external facing handle that is an opaque `rocr::AMD::core::MemoryHandle`.

What we need to abstract is a uint32_t for the XDNA handles and amdgpu_bo_handle for the KFD handles, which is a pointer. I am thinking that having a `using bo_handle_t = uint64_t;` should be good enough to handle both cases.

2024-09-17 00:45 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +__forceinline int mmap_perm(hsa_access_permission_t perms) {
It's common between CPU and AIE agents. The KFD has a different set of enums.

2024-09-17 00:46 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/inc/agent.h
>  // Copyright (c) 2014-2020, Advanced Micro Devices, Inc. All rights reserved.
Yes. That was the format script btw.

2024-09-17 00:50 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_gpu_agent.cpp
> +const uint32_t GpuAgent::minAqlSize_;
It's a -Og / -O1-3 quirk: std::min takes arguments by reference, and I think that the inlining hides the fact that you a pointer in the generated code. It shouldn't happen, but C++ :)

2024-09-17 00:50 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<core::Agent*> whitelist_gpus;
OK, I'll take it to the public ROCR.

2024-09-17 00:56 UTC, atgutier commented on runtime/hsa-runtime/core/inc/agent.h
> +  virtual hsa_status_t Map(void *handle, void *va, size_t offset, size_t size,
Yeah, there are some things we need to think about wrt the driver interface. I think for now I'm more concerned about the interface that lookup overhead. I was actually thinking we should have a reference to the driver object inside the agent. Would that help?

For some of the areas where there already seem to be sidebands thru the Agent, we can rethink those.

2024-09-17 00:56 UTC, atgutier commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<core::Agent*> whitelist_gpus;
David has mentioned to me in the past that we'll need to think about how to add AIEs to these lists. So they should definitely be used somehow. So, yeah get his feedback there.

2024-09-17 00:59 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/inc/agent.h
> +  virtual hsa_status_t Map(void *handle, void *va, size_t offset, size_t size,
I was planning to do the driver lookup at XdnaAgent construction and store it as a pointer since the driver is guaranteed to exist and outlasts the lifetime of the agent.

2024-09-17 18:07 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +__forceinline int mmap_perm(hsa_access_permission_t perms) {
Solved in 4615896c862372610dc2901ddc5f4894bea4faf6

2024-09-17 18:58 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +hsa_status_t XdnaDriver::ImportDMABuf(int dmabuf_fd, uint32_t *handle) {
Resolved in d0f6ebdb68bd09dc3d4398e0af373ac568e9d504

2024-09-17 19:11 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/runtime/amd_aie_agent.cpp
> +  auto &driver = static_cast<XdnaDriver &>(
Resolved in ff002303f1bcf19e860eb5705dd0e674f0175f32

2024-09-17 19:12 UTC, ypapadop-amd commented on runtime/hsa-runtime/core/inc/agent.h
> +  virtual hsa_status_t Map(void *handle, void *va, size_t offset, size_t size,
> I was actually thinking we should have a reference to the driver object inside the agent. Would that help?

AIEAgents have now a pointer to their driver in ff002303f1bcf19e860eb5705dd0e674f0175f32

2024-09-18 20:14 UTC, dayatsin-amd commented on runtime/hsa-runtime/core/runtime/amd_memory_region.cpp
> -  std::set<core::Agent*> whitelist_gpus;
Yes, it does look like whitelist_gpus are not used anymore and we forgot to remove them at some point. Feel free to remove them.

atgutier: I think you are talking about the rvd filers in amd_topology.c. A user can export an environment variable: ROCR_VISIBLE_DEVICES=0,2 on a system with lets say 3 GPUs, and this will effectively hide the second GPU to the users of ROCr (i.e the device will not be listed when someone uses the iterate_agents APIs).
It does look like the whitelist_gpus was used to keep track of visible gpus at some point and affects when initDma() was called, but this is not necessary anymore.

2024-09-19 15:20 UTC, ypapadop-amd commented
Test will fail until https://github.com/nod-ai/ROCR-Runtime/commit/0d7758386b3aada16d9b5593b1c8493081f061b2 is merged.

Is there any reason not to sync the repo with ROCR-Runtime:amd-staging and merge in amd-staging to the iree-aie branch?

2024-10-01 15:53 UTC, ypapadop-amd commented
@makslevental are we planning to keep https://github.com/nod-ai/ROCR-Runtime/tree/iree-aie in sync with https://github.com/ROCm/ROCR-Runtime/tree/amd-staging or should I just cherry-pick https://github.com/nod-ai/ROCR-Runtime/commit/0d7758386b3aada16d9b5593b1c8493081f061b2?

@atgutier what would you like to do to move this forward?

2024-10-01 23:10 UTC, atgutier commented on runtime/hsa-runtime/core/driver/xdna/amd_xdna_driver.cpp
> +  if (mapped_ptr != va)
This doesn't seem correct. Are we trying to enforce a policy where the VA hint has to be mandatory or only use this to map buffer objects where we expect the VA hint to be respected? If so that would require an extra parameter or a less general Map call. Otherwise on success we could get a mapped_ptr value that is not equal the VA.

I think we should be checking for:


`if (mapped_ptr == MAP_FAILED)`

2024-10-01 23:15 UTC, atgutier commented
> @makslevental are we planning to keep https://github.com/nod-ai/ROCR-Runtime/tree/iree-aie in sync with https://github.com/ROCm/ROCR-Runtime/tree/amd-staging or should I just cherry-pick [0d77583](https://github.com/nod-ai/ROCR-Runtime/commit/0d7758386b3aada16d9b5593b1c8493081f061b2)?
> 
> @atgutier what would you like to do to move this forward?

I was able to get all my changes in. As of last week, none are left. I am planning to start addressing some of Ben's requests for additions in ROCr and working to finalize the driver interface/add supports for some of the newer features coming in the xdna-driver.

That said, I don't think you need to cherry-pick anything. I was hoping we'd keep amd-staging clean and make PRs directly into ROCm/ROCR-Runtime when we wanted to get them into amd-staging. You could probably create a PR just for this change.

2024-11-15 20:47 UTC, ypapadop-amd commented
All code-specific comments have been addressed, except if the API changes should be in the Driver or the Agent. The branch is moving to https://github.com/ypapadop-amd/ROCR-Runtime/tree/aie-vmem-dmabuf

2024-11-15 20:47 UTC, closed without merging